{% if theme.passage_end_tag.enabled %}
<div style="text-align:center;color: #ccc;font-size:14px;">
------ 本文结束 ------</div>
<br/>
<div style="border: 2px solid black">
<div style="margin-left:10px">
<span style="font-weight:blod">版权声明</span>
<br/>
由<a href="https://blog.xujiumingcom" style="color:#258FC6">ming</a>创作并维护,</a>博客采用<a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" style="color:#258FC6">CC协议</a>。<br/>
本文首发于<a href="https://blog.xujiumingcom" style="color:#258FC6">ming</a> 博客（ <a href="https://blog.xujiumingcom" style="color:#258FC6">https://blog.xujiumingcom</a> ），版权所有，转载请注明出处！</p>
</div>
</div>
{% endif %}
