version: '3.3'
services:
  ming-service:
    image: ming
    ports:
    - 80:8080
    networks:
    - ming-networks
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  ming-db:
    image: postgres:10.5-alpine
    networks:
    - ming-networks
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  ming-networks:
    driver: overlay
    ipam:
      driver: default
      config:
      - subnet: 10.88.0.0/16
