# 参考: https://www.jianshu.com/p/99952652b2dd
name: sync-oss
# 初期监听push事件  后续按情况调整
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - uses: actions/checkout@v1
      # 安装node 指定版本
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: 开始部署ming-blog
        run: |
          curl 'https://oapi.dingtalk.com/robot/send?access_token=${{ secrets.DINGTALK_ACCESS_TOKEN }}' -H 'Content-Type: application/json' -d '{"msgtype": "text",
                          "text": {
                               "content": "ming-blog开始部署"
                          }
                        }'
      # 构建
      - name: 构建hexo博客
        run: |
          npm install
          hexo generate
      # 使用oss util 复制dist目录到oss
      - uses: manyuanrong/setup-ossutil@v1.0
        with:
          # endpoint 可以去oss控制台上查看
          endpoint: "oss-cn-shanghai.aliyuncs.com"
          # 使用我们之前配置在secrets里面的accesskeys来配置ossutil
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      - name: 同步dist文件到oss上
        run: ossutil cp public/ oss://ming-blog/ -rf
      - name: 成功通知
        if: success()
        run: |
          curl 'https://oapi.dingtalk.com/robot/send?access_token=${{ secrets.DINGTALK_ACCESS_TOKEN }}' -H 'Content-Type: application/json' -d '{"msgtype": "text",
                                      "text": {
                                           "content": "ming-blog部署成功"
                                      }
                                            }'
      - name: 失败通知
        if: failure()
        run: |
          curl 'https://oapi.dingtalk.com/robot/send?access_token=${{ secrets.DINGTALK_ACCESS_TOKEN }}' -H 'Content-Type: application/json' -d '{"msgtype": "text",
                                      "text": {
                                           "content": "ming-blog部署失败!请登录github查看"
                                      }
                                            }'
